# docker-compose.yml
services:
  rtsp-server:
    image: bluenviron/mediamtx
    container_name: rtsp-server
    ports:
      - "46458:8554" 
    restart: always

  ffmpeg-relay:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: ffmpeg-relay
    depends_on:
      - rtsp-server
    volumes:
      # QUAN TRỌNG: Đảm bảo bạn có 2 file video ở thư mục ../../sampleTest
      - ../../sampleTest/vid_test_1.mp4:/videos/vid_test_1.mp4:ro
      - ../../sampleTest/vid_test_2.mp4:/videos/vid_test_2.mp4:ro
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ffmpeg -re -stream_loop -1 -err_detect ignore_err -i /videos/vid_test_1.mp4 -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://rtsp-server:8554/mystream1
      & ffmpeg -re -stream_loop -1 -err_detect ignore_err -i /videos/vid_test_2.mp4 -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp rtsp://rtsp-server:8554/mystream2
      && wait"
  
  db:
    image: mysql:9.4 
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: rtsp_db
    ports:
      - "3306:3306" # Dùng cổng chuẩn 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: . # Đường dẫn đến Dockerfile
    container_name: face_recognition_app
    depends_on:
      rtsp-server:
        condition: service_started
      db:
        condition: service_healthy # Đợi DB sẵn sàng
    ports:
      - "8000:8000" # Mở cổng FastAPI 8000
    volumes:
      - .:/app  # Mount code hiện tại vào /app để live-reload
    working_dir: /app 
    environment:
      - DB_HOST=db  # 'db' là tên của service MySQL ở trên
      - DB_USER=root
      - DB_PASS=12345
      - DB_NAME=rtsp_db
      - PYTHONPATH=/app
    
    # GHI ĐÈ LỆNH CMD CỦA DOCKERFILE
    # Chúng ta dùng "uvicorn --reload" để code tự cập nhật khi ta sửa file mẫu nâng cao
    command: >
      uvicorn server:app 
      --host 0.0.0.0 
      --port 8000 
      --reload
    
    # Kích hoạt GPU (nếu có)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]